
python convertXMP.py  "xmpPresets//Trey/The Navigator.xmp" "jsonPresets//Trey/Navigator.json"
python convertXMP.py   "xmpPresets//Trey/Relic.xmp" "jsonPresets//Trey/Relic.json"
python convertXMP.py    "xmpPresets//Trey/On Recreational Drugs.xmp" "jsonPresets//Trey/OnRecreationalDrugs.json"
python convertXMP.py    "xmpPresets//Trey/Turkish Blast.xmp" "jsonPresets//Trey/TurkishBlast.json"
python convertXMP.py    "xmpPresets//Trey/Thank Heaven for Little Girls.xmp" "jsonPresets//Trey/ThankHeavenForLittleGirls.json"
python convertXMP.py    "xmpPresets//Trey/Sunday Alone Time.xmp" "jsonPresets//Trey/SundayAloneTime.json"
python convertXMP.py    "xmpPresets//Trey/Carefully Shaven Turk.xmp" "jsonPresets//Trey/CarefullyShavenTurk.json"
python convertXMP.py    "xmpPresets//Trey/A Marshmallow Happysmell.xmp" "jsonPresets//Trey/MarshmallowHappysmell.json"
python convertXMP.py    "xmpPresets//Trey/Steampunk Afternoon.xmp" "jsonPresets//Trey/SteampunkAfternoon.json"
python convertXMP.py    "xmpPresets//Trey/A Beautiful Release.xmp" "jsonPresets//Trey/BeautifulRelease.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Vicky.xmp" "jsonPresets//BlondiesBrunettes/Vicky.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Summer.xmp" "jsonPresets//BlondiesBrunettes/Summer.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Marianne.xmp" "jsonPresets//BlondiesBrunettes/Marianne.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Gwendolyn.xmp" "jsonPresets//BlondiesBrunettes/Gwendolyn.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Taylor.xmp" "jsonPresets//BlondiesBrunettes/Taylor.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Adeline.xmp" "jsonPresets//BlondiesBrunettes/Adeline.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Amber.xmp" "jsonPresets//BlondiesBrunettes/Amber.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Emily.xmp" "jsonPresets//BlondiesBrunettes/Emily.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Violet.xmp" "jsonPresets//BlondiesBrunettes/Violet.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Juliet.xmp" "jsonPresets//BlondiesBrunettes/Juliet.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Clarisse.xmp" "jsonPresets//BlondiesBrunettes/Clarisse.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Urban Grain.xmp" "jsonPresets//F-StopUrban/UrbanGrain.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge.xmp" "jsonPresets//F-StopUrban/Grunge.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (blue).xmp" "jsonPresets//F-StopUrban/GrungeBlue.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (smooth).xmp" "jsonPresets//F-StopUrban/GrungeSmooth.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (sepia).xmp" "jsonPresets//F-StopUrban/GrungeSepia.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Urban Vignette.xmp" "jsonPresets//F-StopUrban/UrbanVignette.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (green).xmp" "jsonPresets//F-StopUrban/GrungeGreen.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (muted).xmp" "jsonPresets//F-StopUrban/GrungeMuted.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (red).xmp" "jsonPresets//F-StopUrban/GrungeRed.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (black & white).xmp" "jsonPresets//F-StopUrban/GrungeBW.json"
