
python convertXMP.py  "xmpPresets//Trey/The Navigator.xmp" "../phixer/Config/Presets/Trey/Navigator.json"
python convertXMP.py   "xmpPresets//Trey/Relic.xmp" "../phixer/Config/Presets/Trey/Relic.json"
python convertXMP.py    "xmpPresets//Trey/On Recreational Drugs.xmp" "../phixer/Config/Presets/Trey/OnRecreationalDrugs.json"
python convertXMP.py    "xmpPresets//Trey/Turkish Blast.xmp" "../phixer/Config/Presets/Trey/TurkishBlast.json"
python convertXMP.py    "xmpPresets//Trey/Thank Heaven for Little Girls.xmp" "../phixer/Config/Presets/Trey/ThankHeavenForLittleGirls.json"
python convertXMP.py    "xmpPresets//Trey/Sunday Alone Time.xmp" "../phixer/Config/Presets/Trey/SundayAloneTime.json"
python convertXMP.py    "xmpPresets//Trey/Carefully Shaven Turk.xmp" "../phixer/Config/Presets/Trey/CarefullyShavenTurk.json"
python convertXMP.py    "xmpPresets//Trey/A Marshmallow Happysmell.xmp" "../phixer/Config/Presets/Trey/MarshmallowHappysmell.json"
python convertXMP.py    "xmpPresets//Trey/Steampunk Afternoon.xmp" "../phixer/Config/Presets/Trey/SteampunkAfternoon.json"
python convertXMP.py    "xmpPresets//Trey/A Beautiful Release.xmp" "../phixer/Config/Presets/Trey/BeautifulRelease.json"

python convertXMP.py    "xmpPresets//BlondiesBrunettes/Vicky.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Vicky.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Summer.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Summer.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Marianne.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Marianne.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Gwendolyn.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Gwendolyn.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Taylor.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Taylor.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Adeline.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Adeline.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Amber.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Amber.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Emily.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Emily.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Violet.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Violet.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Juliet.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Juliet.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Clarisse.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Clarisse.json"

python convertXMP.py    "xmpPresets//F-StopUrban/Urban Grain.xmp" "../phixer/Config/Presets/F-StopUrban/UrbanGrain.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge.xmp" "../phixer/Config/Presets/F-StopUrban/Grunge.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (blue).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeBlue.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (smooth).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeSmooth.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (sepia).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeSepia.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Urban Vignette.xmp" "../phixer/Config/Presets/F-StopUrban/UrbanVignette.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (green).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeGreen.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (muted).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeMuted.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (red).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeRed.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (black & white).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeBW.json"

python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji 400H.xmp" "../phixer/Config/Presets/AnalogFilm/Fuji400H.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Superia 400.xmp" "../phixer/Config/Presets/AnalogFilm/FujiSuperia400.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Superia 1600.xmp" "../phixer/Config/Presets/AnalogFilm/FujiSuperia1600.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Velvia 50.xmp" "../phixer/Config/Presets/AnalogFilm/FujiVelvia50.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Velvia 100.xmp" "../phixer/Config/Presets/AnalogFilm/FujiVelvia100.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak Ektar 100.xmp" "../phixer/Config/Presets/AnalogFilm/KodakEktar100.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak Portra 400.xmp" "../phixer/Config/Presets/AnalogFilm/KodakPortra400.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak Portra 800.xmp" "../phixer/Config/Presets/AnalogFilm/KodakPortra800.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak T-MAX 3200.xmp" "../phixer/Config/Presets/AnalogFilm/KodakTMAX3200.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak TRI-X 400.xmp" "../phixer/Config/Presets/AnalogFilm/KodakTriX400.json"

python convertXMP.py     "./xmpPresets/onOne X-Process LR5/Cross Process Green.xmp" "../phixer/Config/Presets/onOneXProcess/CrossProcessGreen.json"
python convertXMP.py     "./xmpPresets/onOne X-Process LR5/Cross Process Blue.xmp" "../phixer/Config/Presets/onOneXProcess/CrossProcessBlue.json"
python convertXMP.py     "./xmpPresets/onOne X-Process LR5/Cross Process Yellow.xmp" "../phixer/Config/Presets/onOneXProcess/CrossProcessYellow.json"

python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 3-Tone-Tint - Nice Greens.xmp" "../phixer/Config/Presets/Sleeklens/NiceGreens.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 0-All in One - Fresh Lime.xmp" "../phixer/Config/Presets/Sleeklens/FreshLime.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 4-Polish - High Contrast.xmp" "../phixer/Config/Presets/Sleeklens/HighContrast.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 2-Exposure - Open Shadows.xmp" "../phixer/Config/Presets/Sleeklens/OpenShadows.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 5-Vintage - Velvet Freedom.xmp" "../phixer/Config/Presets/Sleeklens/VelvetFreedom.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 4-Polish - Low Contrast.xmp" "../phixer/Config/Presets/Sleeklens/LowContrast.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 6-Black&White - Vintage Black.xmp" "../phixer/Config/Presets/Sleeklens/VintageBlack.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 7-Vignette - Subtle White.xmp" "../phixer/Config/Presets/Sleeklens/SubtleWhite.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 0-All in One - Happy Meadow.xmp" "../phixer/Config/Presets/Sleeklens/HappyMeadow.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 1-Base - Afternoon Play.xmp" "../phixer/Config/Presets/Sleeklens/AfternoonPlay.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 3-Tone-Tint - Sunny Vibe.xmp" "../phixer/Config/Presets/Sleeklens/SunnyVibe.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 2-Exposure - Close Highlights.xmp" "../phixer/Config/Presets/Sleeklens/CloseHighlights.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 1-Base - Rainy Days.xmp" "../phixer/Config/Presets/Sleeklens/RainyDays.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 5-Vintage - Green Cotton.xmp" "../phixer/Config/Presets/Sleeklens/GreenCotton.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 3-Tone-Tint - Hawai Color.xmp" "../phixer/Config/Presets/Sleeklens/HawaiColor.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 5-Vintage - Dreamy Feeling.xmp" "../phixer/Config/Presets/Sleeklens/DreamyFeeling.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 2-Exposure - Open Highlights.xmp" "../phixer/Config/Presets/Sleeklens/OpenHighlights.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 2-Exposure - Exposure +1.xmp" "../phixer/Config/Presets/Sleeklens/ExposurePlus1.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 4-Polish - Color Pop.xmp" "../phixer/Config/Presets/Sleeklens/ColorPop.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 6-Black&White - Clean Black.xmp" "../phixer/Config/Presets/Sleeklens/CleanBlack.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 7-Vignette - Subtle Black.xmp" "../phixer/Config/Presets/Sleeklens/SubtleBlack.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 6-Black&White - Startrails.xmp" "../phixer/Config/Presets/Sleeklens/Startrails.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 6-Black&White - Grey World.xmp" "../phixer/Config/Presets/Sleeklens/GreyWorld.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 5-Vintage - Travel Wish.xmp" "../phixer/Config/Presets/Sleeklens/TravelWish.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 5-Vintage - Summer Bloom.xmp" "../phixer/Config/Presets/Sleeklens/SummerBloom.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 3-Tone-Tint - Warm Shadows.xmp" "../phixer/Config/Presets/Sleeklens/WarmShadows.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 2-Exposure - Close Shadows.xmp" "../phixer/Config/Presets/Sleeklens/CloseShadows.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 1-Base - Kasper.xmp" "../phixer/Config/Presets/Sleeklens/Kasper.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 2-Exposure - Exposure -1.xmp" "../phixer/Config/Presets/Sleeklens/ExposureMinus1.json"
python convertXMP.py     "./xmpPresets/Sleeklens Starter Presets/Sleeklens Starter - 0-All in One - Walk On A Beach.xmp" "../phixer/Config/Presets/Sleeklens/WalkOnABeach.json"

python convertXMP.py     "./xmpPresets/onOne Vintage LR5/Vintage Cool.xmp" "../phixer/Config/Presets/onOneVintage/VintageCool.json"
python convertXMP.py     "./xmpPresets/onOne Vintage LR5/Vintage Red Cyan.xmp" "../phixer/Config/Presets/onOneVintage/VintageRedCyan.json"
python convertXMP.py     "./xmpPresets/onOne Vintage LR5/Vintage Red.xmp" "../phixer/Config/Presets/onOneVintage/VintageRed.json"
python convertXMP.py     "./xmpPresets/onOne Vintage LR5/Vintage Blue Yellow.xmp" "../phixer/Config/Presets/onOneVintage/VintageBlueYellow.json"

python convertXMP.py     "./xmpPresets/onOne Movie Looks LR5/Wonka.xmp" "../phixer/Config/Presets/onOneMovieLooks/Wonka.json"
python convertXMP.py     "./xmpPresets/onOne Movie Looks LR5/Blue Dawn.xmp" "../phixer/Config/Presets/onOneMovieLooks/BlueDawn.json"
python convertXMP.py     "./xmpPresets/onOne Movie Looks LR5/Arkham.xmp" "../phixer/Config/Presets/onOneMovieLooks/Arkham.json"
python convertXMP.py     "./xmpPresets/onOne Movie Looks LR5/Omaha Beach.xmp" "../phixer/Config/Presets/onOneMovieLooks/OmahaBeach.json"
python convertXMP.py     "./xmpPresets/onOne Movie Looks LR5/Tijuana.xmp" "../phixer/Config/Presets/onOneMovieLooks/Tijuana.json"


python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Daisy.xmp" "../phixer/Config/Presets/onOneInstantastic/Daisy.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Robin.xmp" "../phixer/Config/Presets/onOneInstantastic/Robin.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Inky.xmp" "../phixer/Config/Presets/onOneInstantastic/Inky.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Roaster.xmp" "../phixer/Config/Presets/onOneInstantastic/Roaster.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/1975.xmp" "../phixer/Config/Presets/onOneInstantastic/1975.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/El Hefe.xmp" "../phixer/Config/Presets/onOneInstantastic/ElHefe.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Crossify.xmp" "../phixer/Config/Presets/onOneInstantastic/Crossify.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Walden Pond.xmp" "../phixer/Config/Presets/onOneInstantastic/WaldenPond.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/XPro.xmp" "../phixer/Config/Presets/onOneInstantastic/XPro.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Brandenburg.xmp" "../phixer/Config/Presets/onOneInstantastic/Brandenburg.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Lord Kelvin.xmp" "../phixer/Config/Presets/onOneInstantastic/LordKelvin.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Pop Flash.xmp" "../phixer/Config/Presets/onOneInstantastic/PopFlash.json"
python convertXMP.py     "./xmpPresets/onOne Instantastic LR5/Mayor.xmp" "../phixer/Config/Presets/onOneInstantastic/Mayor.json"

