
python convertXMP.py  "xmpPresets//Trey/The Navigator.xmp" "../phixer/Config/Presets/Trey/Navigator.json"
python convertXMP.py   "xmpPresets//Trey/Relic.xmp" "../phixer/Config/Presets/Trey/Relic.json"
python convertXMP.py    "xmpPresets//Trey/On Recreational Drugs.xmp" "../phixer/Config/Presets/Trey/OnRecreationalDrugs.json"
python convertXMP.py    "xmpPresets//Trey/Turkish Blast.xmp" "../phixer/Config/Presets/Trey/TurkishBlast.json"
python convertXMP.py    "xmpPresets//Trey/Thank Heaven for Little Girls.xmp" "../phixer/Config/Presets/Trey/ThankHeavenForLittleGirls.json"
python convertXMP.py    "xmpPresets//Trey/Sunday Alone Time.xmp" "../phixer/Config/Presets/Trey/SundayAloneTime.json"
python convertXMP.py    "xmpPresets//Trey/Carefully Shaven Turk.xmp" "../phixer/Config/Presets/Trey/CarefullyShavenTurk.json"
python convertXMP.py    "xmpPresets//Trey/A Marshmallow Happysmell.xmp" "../phixer/Config/Presets/Trey/MarshmallowHappysmell.json"
python convertXMP.py    "xmpPresets//Trey/Steampunk Afternoon.xmp" "../phixer/Config/Presets/Trey/SteampunkAfternoon.json"
python convertXMP.py    "xmpPresets//Trey/A Beautiful Release.xmp" "../phixer/Config/Presets/Trey/BeautifulRelease.json"

python convertXMP.py    "xmpPresets//BlondiesBrunettes/Vicky.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Vicky.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Summer.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Summer.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Marianne.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Marianne.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Gwendolyn.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Gwendolyn.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Taylor.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Taylor.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Adeline.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Adeline.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Amber.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Amber.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Emily.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Emily.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Violet.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Violet.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Juliet.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Juliet.json"
python convertXMP.py    "xmpPresets//BlondiesBrunettes/Clarisse.xmp" "../phixer/Config/Presets/BlondiesBrunettes/Clarisse.json"

python convertXMP.py    "xmpPresets//F-StopUrban/Urban Grain.xmp" "../phixer/Config/Presets/F-StopUrban/UrbanGrain.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge.xmp" "../phixer/Config/Presets/F-StopUrban/Grunge.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (blue).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeBlue.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (smooth).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeSmooth.json"
python convertXMP.py    "xmpPresets//F-StopUrban/Grunge (sepia).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeSepia.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Urban Vignette.xmp" "../phixer/Config/Presets/F-StopUrban/UrbanVignette.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (green).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeGreen.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (muted).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeMuted.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (red).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeRed.json"
python convertXMP.py     "xmpPresets//F-StopUrban/Grunge (black & white).xmp" "../phixer/Config/Presets/F-StopUrban/GrungeBW.json"

python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji 400H.xmp" "../phixer/Config/Presets/AnalogFilm/Fuji400H.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Superia 400.xmp" "../phixer/Config/Presets/AnalogFilm/FujiSuperia400.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Superia 1600.xmp" "../phixer/Config/Presets/AnalogFilm/FujiSuperia1600.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Velvia 50.xmp" "../phixer/Config/Presets/AnalogFilm/FujiVelvia50.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Fuji Velvia 100.xmp" "../phixer/Config/Presets/AnalogFilm/FujiVelvia100.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak Ektar 100.xmp" "../phixer/Config/Presets/AnalogFilm/KodakEktar100.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak Portra 400.xmp" "../phixer/Config/Presets/AnalogFilm/KodakPortra400.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak Portra 800.xmp" "../phixer/Config/Presets/AnalogFilm/KodakPortra800.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak T-MAX 3200.xmp" "../phixer/Config/Presets/AnalogFilm/KodakTMAX3200.json"
python convertXMP.py     "xmpPresets/AnalogFilm/N - Kodak TRI-X 400.xmp" "../phixer/Config/Presets/AnalogFilm/KodakTriX400.json"

